"""empty message

Revision ID: 54ad20e69276
Revises: b62d1b593a26
Create Date: 2025-03-25 16:40:13.763164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54ad20e69276'
down_revision = 'b62d1b593a26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('num_guests', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_request_id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('host_confirmed', sa.Boolean(), nullable=True),
    sa.Column('student_confirmed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['student_request_id'], ['student_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('preferences', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('location', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'location')
    op.drop_column('user', 'preferences')
    op.drop_column('user', 'about_me')
    op.drop_table('match')
    op.drop_table('student_request')
    # ### end Alembic commands ###
